menu_settings:
  menu_items:
    # - title: 'AI Risk Discussions'
    #   url: '/ai-risk-discussions'
    #   fade: true
    #   submenu: 
    #     - title: 'AI Risk Discussions'
    #       url: '/ai-risk-discussions'
    #     - title: 'Perspectives'
    #       url: '/perspectives/introduction'
    #     - title: 'Interviews'
    #       url: '/interviews'
    - title: About
      url: '/about'
    - title: Papers
      url: '/papers'
    - title: Resources
      #title: Resource Center
      shorttitle: Resources
      url: '/resources'
      submenu:
        - title: 'Opportunities'
          url: '/resources#opportunities'
        - title: 'AI Safety'
          url: '/resources#ai_safety'
    - title: 'Request a Call'
      url: 'https://airtable.com/appPMHlJ6Z7XkDSEi/shr8RR0ZkJr22Ub3Z'
      # this isn't working: {{site.applyur}}'
      button: true
      hidden: false
    # - title: 'Apply For A Call'
    #   url: '/apply'
    #   button: true
    #   hidden: true
