menu_settings:
  menu_items:
    # - title: 'AI Risk Discussions'
    #   url: '/ai-risk-discussions'
    #   fade: true
    #   submenu: 
    #     - title: 'AI Risk Discussions'
    #       url: '/ai-risk-discussions'
    #     - title: 'Perspectives'
    #       url: '/perspectives/introduction'
    #     - title: 'Interviews'
    #       url: '/interviews'
    - title: About
      url: '/about'
    - title: AI Safety Papers
      url: '/aisafety'
    - title: Opportunities
      #title: Resource Center
      shorttitle: Opportunities
      url: '/opportunities'
    - title: 'Connections'
      new_tab: true
      url: '/connections'
    - title: 'Request a Call' # Note that if you change this text, you need to change in header.html
      url: 'https://airtable.com/appPMHlJ6Z7XkDSEi/shr8RR0ZkJr22Ub3Z'
      # this isn't working: {{site.applyur}}'
      button: true
      hidden: false
    # - title: 'Apply For A Call'
    #   url: '/apply'
    #   button: true
    #   hidden: true
